spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul # jdbc:mysql://localhost:3306/{데이터베이스명} + 이모지 대응 코드
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호
  sql:
    init:
      mode: always

  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅
    defer-datasource-initialization: true

  ai:
    openai:
      api-key: ${GEMINI_API_KEY:} # : 붙여서 환경변수가 없으면 빈 값으로 처리(에러 방지)

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: "this-is-remu-project-local-secret-key-for-jwt-testing-12345678"